So I have a very curious feeling as I am writing all this down. The
atmosphere seems filled with a stimulating fragrance of flowers,
which overcomes me and gives me a headache. The smoke of the
fireplace curls and condenses into figures, small gray-bearded
kokolds that mockingly point their finger at me. Chubby-cheeked
cupids ride on the arms of my chair and on my knees. I have to smile
involuntarily, even laugh aloud, as I am writing down my adventures.
Yet I am not writing with ordinary ink, but with red blood that drips
from my heart. All its wounds long scarred over have opened and it
throbs and hurts, and now and then a tear falls on the paper.

The days creep along sluggishly in the little Carpathian health-
resort. You see no one, and no one sees you. It is boring enough to
write idyls. I would have leisure here to supply a whole gallery of
paintings, furnish a theater with new pieces for an entire season,
a dozen virtuosos with concertos, trios, and duos, but--what am I
saying--the upshot of it all is that I don't do much more than to
stretch the canvas, smooth the bow, line the scores. For I am--no
false modesty, Friend Severin; you can lie to others, but you don't
quite succeed any longer in lying to yourself--I am nothing but a
dilettante, a dilettante in painting, in poetry, in music, and
several other of the so-called unprofitable arts, which, however, at
present secure for their masters the income of a cabinet minister,
or even that of a minor potentate. Above all else I am a dilettante
in life.

Up to the present I have lived as I have painted and written poetry.
I never got far beyond the preparation, the plan, the first act, the
first stanza. There are people like that who begin everything, and
never finish anything. I am such a one.

But what am I saying?

To the business in hand.

I lie in my window, and the miserable little town, which fills me
with despondency, really seems infinitely full of poetry. How
wonderful the outlook upon the blue wall of high mountains interwoven
with golden sunlight; mountain-torrents weave through them like
ribbons of silver! How clear and blue the heavens into which
snowcapped crags project; how green and fresh the forested slopes;
the meadows on which small herds graze, down to the yellow billows
of grain where reapers stand and bend over and rise up again.

The house in which I live stands in a sort of park, or forest, or
wilderness, whatever one wants to call it, and is very solitary.

Its sole inhabitants are myself, a widow from Lemberg, and Madame
Tartakovska, who runs the house, a little old woman, who grows older
and smaller each day. There are also an old dog that limps on one
leg, and a young cat that continually plays with a ball of yarn. This
ball of yarn, I believe, belongs to the widow.

She is said to be really beautiful, this widow, still very young,
twenty-four at the most, and very rich. She dwells in the first
story, and I on the ground floor. She always keeps the green blinds
drawn, and has a balcony entirely overgrown with green climbing-
plants. I for my part down below have a comfortable, intimate arbor
of honeysuckle, in which I read and write and paint and sing like a
bird among the twigs. I can look up on the balcony. Sometimes I
actually do so, and then from time to time a white gown gleams
between the dense green network.

Really the beautiful woman up there doesn't interest me very much,
for I am in love with someone else, and terribly unhappy at that; far
more unhappy than the Knight of Toggenburg or the Chevalier in Manon
l'Escault, because the object of my adoration is of stone.

In the garden, in the tiny wilderness, there is a graceful little
meadow on which a couple of deer graze peacefully. On this meadow is
a stone statue of Venus, the original of which, I believe, is in
Florence. This Venus is the most beautiful woman I have ever seen in
all my life.

That, however, does not signify much, for I have seen few beautiful
women, or rather few women at all. In love too, I am a dilettante who
never got beyond the preparation, the first act.

But why talk in superlatives, as if something that is beautiful
could be surpassed?

It is sufficient to say that this Venus is beautiful. I love her
passionately with a morbid intensity; madly as one can only love a
woman who never responds to our love with anything but an eternally
uniform, eternally calm, stony smile. I literally adore her.

I often lie reading under the leafy covering of a young birch when
the sun broods over the forest. Often I visit that cold, cruel
mistress of mine by night and lie on my knees before her, with the
face pressed against the cold pedestal on which her feet rest, and
my prayers go up to her.

The rising moon, which just now is waning, produces an indescribable
effect. It seems to hover among the trees and submerges the meadow
in its gleam of silver. The goddess stands as if transfigured, and
seems to bathe in the soft moonlight.

Once when I was returning from my devotions by one of the walks
leading to the house, I suddenly saw a woman's figure, white as
stone, under the illumination of the moon and separated from me
merely by a screen of trees. It seemed as if the beautiful woman of
marble had taken pity on me, become alive, and followed me. I was
seized by a nameless fear, my heart threatened to burst, and instead--

Well, I am a dilettante. As always, I broke down at the second
stanza; rather, on the contrary, I did not break down, but ran away
as fast as my legs would carry me.

       *       *       *       *       *

What an accident! Through a Jew, dealing in photographs I secured a
picture of my ideal. It is a small reproduction of Titian's "Venus
with the Mirror." What a woman! I want to write a poem, but instead,
I take the reproduction, and write on it: _Venus in Furs_.

You are cold, while you yourself fan flames. By all means wrap
yourself in your despotic furs, there is no one to whom they are more
appropriate, cruel goddess of love and of beauty!--After a while I add
a few verses from Goethe, which I recently found in his paralipomena
to _Faust_.

  TO AMOR

  "The pair of wings a fiction are,
   The arrows, they are naught but claws,
   The wreath conceals the little horns,
   For without any doubt he is
   Like all the gods of ancient Greece
   Only a devil in disguise."

Then I put the picture before me on my table, supporting it with a
book, and looked at it.

I was enraptured and at the same time filled with a strange fear by
the cold coquetry with which this magnificent woman draped her charms
in her furs of dark sable; by the severity and hardness which lay in
this cold marble-like face. Again I took my pen in hand, and wrote
the following words:

"To love, to be loved, what happiness! And yet how the glamour of
this pales in comparison with the tormenting bliss of worshipping a
woman who makes a plaything out of us, of being the slave of a
beautiful tyrant who treads us pitilessly underfoot. Even Samson, the
hero, the giant, again put himself into the hands of Delilah, even
after she had betrayed him, and again she betrayed him, and the
Philistines bound him and put out his eyes which until the very end
he kept fixed, drunken with rage and love, upon the beautiful
betrayer."

I was breakfasting in my honey-suckle arbor, and reading in the Book
of Judith. I envied the hero Holofernes because of the regal woman
who cut off his head with a sword, and because of his beautiful
sanguinary end.

"The almighty Lord hath struck him, and hath delivered him into the
hands of a woman."

This sentence strangely impressed me.

How ungallant these Jews are, I thought. And their God might choose
more becoming expressions when he speaks of the fair sex.

"The almighty Lord hath struck him, and hath delivered him into the
hands of a woman," I repeated to myself. What shall I do, so that He
may punish me?

Heaven preserve us! Here comes the housekeeper, who has again
diminished somewhat in size overnight. And up there among the green
twinings and garlandings the white gown gleams again. Is it Venus,
or the widow?

This time it happens to be the widow, for Madame Tartakovska makes
a courtesy, and asks me in her name for something to read. I run to
my room, and gather together a couple of volumes.

Later I remember that my picture of Venus is in one of them, and now
it and my effusions are in the hands of the white woman up there
together. What will she say?

I hear her laugh.

Is she laughing at me?

It is full moon. It is already peering over the tops of the low
hemlocks that fringe the park. A silvery exhalation fills the
terrace, the groups of trees, all the landscape, as far as the eye
can reach; in the distance it gradually fades away, like trembling
waters.

I cannot resist. I feel a strange urge and call within me. I put on
my clothes again and go out into the garden.

Some power draws me toward the meadow, toward her, who is my
divinity and my beloved.

The night is cool. I feel a slight chill. The atmosphere is heavy
with the odor of flowers and of the forest. It intoxicates.

What solemnity! What music round about! A nightingale sobs. The
stars quiver very faintly in the pale-blue glamour. The meadow seems
smooth, like a mirror, like a covering of ice on a pond.

The statue of Venus stands out august and luminous.

But--what has happened? From the marble shoulders of the goddess a
large dark fur flows down to her heels. I stand dumbfounded and stare
at her in amazement; again an indescribable fear seizes hold of me
and I take flight.

I hasten my steps, and notice that I have missed the main path. As
I am about to turn aside into one of the green walks I see Venus
sitting before me on a stone bench, not the beautiful woman of
marble, but the goddess of love herself with warm blood and throbbing
pulses. She has actually come to life for me, like the statue that
began to breathe for her creator. Indeed, the miracle is only half
completed. Her white hair seems still to be of stone, and her white
gown shimmers like moonlight, or is it satin? From her shoulders the
dark fur flows. But her lips are already reddening and her cheeks
begin to take color. Two diabolical green rays out of her eyes fall
upon me, and now she laughs.

Her laughter is very mysterious, very--I don't know. It cannot be
described, it takes my breath away. I flee further, and after every
few steps I have to pause to take breath. The mocking laughter
pursues me through the dark leafy paths, across light open spaces,
through the thicket where only single moonbeams can pierce. I can no
longer find my way, I wander about utterly confused, with cold drops
of perspiration on the forehead.

Finally I stand still, and engage in a short monologue.

It runs--well--one is either very polite to one's self or very rude.

I say to myself:

"Donkey!"

This word exercises a remarkable effect, like a magic formula, which
sets me free and makes me master of myself.

I am perfectly quiet in a moment.

With considerable pleasure I repeat: "Donkey!"

Now everything is perfectly clear and distinct before my eyes again.
There is the fountain, there the alley of box-wood, there the house
which I am slowly approaching.

Yet--suddenly the appearance is here again. Behind the green screen
through which the moonlight gleams so that it seems embroidered with
silver, I again see the white figure, the woman of stone whom I
adore, whom I fear and flee.

With a couple of leaps I am within the house and catch my breath and
reflect.

What am I really, a little dilettante or a great big donkey?

A sultry morning, the atmosphere is dead, heavily laden with odors,
yet stimulating. Again I am sitting in my honey-suckle arbor, reading
in the Odyssey about the beautiful witch who transformed her admirers
into beasts. A wonderful picture of antique love.

There is a soft rustling in the twigs and blades and the pages of my
book rustle and on the terrace likewise there is a rustling.

A woman's dress--

She is there--Venus--but without furs--No, this time it is merely
the widow--and yet--Venus-oh, what a woman!

As she stands there in her light white morning gown, looking at me,
her slight figure seems full of poetry and grace. She is neither
large, nor small; her head is alluring, piquant--in the sense of the
period of the French marquises--rather than formally beautiful. What
enchantment and softness, what roguish charm play about her none too
small mouth! Her skin is so infinitely delicate, that the blue veins
show through everywhere; even through the muslin covering her arms
and bosom. How abundant her red hair-it is red, not blonde or golden-
yellow--how diabolically and yet tenderly it plays around her neck!
Now her eyes meet mine like green lightnings--they are green, these
eyes of hers, whose power is so indescribable--green, but as are
precious stones, or deep unfathomable mountain lakes.

She observes my confusion, which has even made me discourteous, for
I have remained seated and still have my cap on my head.

She smiles roguishly.

Finally I rise and bow to her. She comes closer, and bursts out into
a loud, almost childlike laughter. I stammer, as only a little
dilettante or great big donkey can do on such an occasion.

Thus our acquaintance began.

The divinity asks for my name, and mentions her own.

Her name is Wanda von Dunajew.

And she is actually my Venus.